spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/idle_market?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTime=GMT%2b8
    username: root
    password: root
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
server:
  port: 8090
# mybatis配置
mybatis-plus:
  configuration:
    # 开启sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
    map-underscore-to-camel-case: true
  # 配置逻辑删除值
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0


ip: localhost